application: michaelfallihee
version: 1
runtime: go
api_version: go1

handlers:
- url: /static
  static_dir: static
- url: /post/new
  script: _go_app
  login: admin
- url: /post/add
  script: _go_app
  login: admin
- url: /.*
  script: _go_app